name = "xploits"
compatibility_date = "2026-04-16"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "SCRIPTS"
id = "cac45b1759e445f48f9e8a8d45295126"
preview_id = "cac45b1759e445f48f9e8a8d45295126"
